# -*- coding: utf-8 -*-
"""Data Science Draft 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQy_yxVoubf2LB2mMEiMd77xAW0pdleR

# How Do Weather and Snow Conditions Affect Solar Energy Production?

Anne Mara, Anna Simonelli, and Sam Keller

## Introduction
Solar energy production varies with environmental conditions such as sunlight, cloud cover, and weather. Factors like humidity, precipitation, and snow may affect how much energy solar panels generate on given day.

This dataset includes solar energy production along with daily weather, precipitation, and solar
measurements from 2017 to 2023. Because it includes both atmospheric and snow-related variables, it allows us to explore how different conditions relate to solar output.

We examine how atmospheric and snow-related variables relate to solar energy production and whether these conditions can predict high-output days.

### Import packages
"""

# import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns
import plotly.express as px

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LassoCV
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn import tree, ensemble

"""### Import the data"""

precipitation = pd.read_csv("precipitation.csv")
sun = pd.read_csv("sun.csv")
weather = pd.read_csv("weather.csv")
solar = pd.read_csv("solar.csv")

"""## Data Cleaning

### Investigate the data

We look at the first five rows of each dataset
"""

precipitation.head()

sun.head()

weather.head()

solar.head()

"""We noticed that solar was recorded in 15 minute increments. The other data values are recorded in daily increments. In order to compare the values we decided to aggregate the solar data to a daily sum.

#### Investigate data types
"""

precipitation.info()
sun.info()
weather.info()
solar.info()

"""#### Convert dates to datetime objects"""

# making precipitation's "Date" lowercase to match all datasets
precipitation.rename(columns={"Date": "date"}, inplace=True)

# convert dates to datetime objects
weather['date'] = pd.to_datetime(weather['date'])
precipitation['date'] = pd.to_datetime(precipitation['date'])
sun['date'] = pd.to_datetime(sun['date'])
solar['date'] = pd.to_datetime(solar['date']).dt.normalize()

"""#### Convert columns to numeric"""

cols_to_convert = ['Precip in.', '24-hr Snowfall in.', 'Snowpack Depth in.']
for col in cols_to_convert:
    precipitation[col] = pd.to_numeric(precipitation[col], errors='coerce')

"""#### Aggregate solar values
Precipatation, weather, and sun are all measured daily, but solar is measured every 15 minutes. We are going to aggregate the solar data to be a daily sum
"""

# aggregate values
solar_daily = (
    solar
    .groupby('date', as_index=False)['value']
    .sum()
    .rename(columns={'value': 'solarDailyTotal'})
)

solar_daily.head()

"""#### Merging the datasets"""

# merging the four solar datasets
solar_power = (
    solar_daily
    .merge(weather, on='date', how='inner')
    .merge(precipitation, on='date', how='inner')
    .merge(sun, on='date', how='inner')
)

solar_power.head()

"""#### Rename columns"""

# renaming long columns to shorter names to make accessing easier
solar_power = (
    solar_power
    .rename(
        columns = {
            'Precip in.': 'precip',
            '24-hr Snowfall in.': 'snowfall',
            'Snowpack Depth in.': 'snowpack',
        }
    )
)

"""# EDA"""

solar_power.describe()

numeric_cols = ['solarDailyTotal', 'temperatureMax', 'temperatureMin', 'rainTotal',
                'barometerMax', 'barometerMin', 'cloudMax', 'cloudMin',
                'humidityMax', 'humidityMin', 'precip', 'snowfall',
                'snowpack']

solar_power[numeric_cols].hist(figsize=(15,10), bins=30)
plt.tight_layout()
plt.show()

"""# Question 1: How do atmospheric conditions affect solary energy production (cloud cover, humidity, precipitation, and barometric pressure)?

#### Feature Engineering
"""

solar_power['cloudAvg'] = (solar_power['cloudMax'] + solar_power['cloudMin']) / 2
solar_power['humidityAvg'] = (solar_power['humidityMax'] + solar_power['humidityMin']) / 2
solar_power['barometerAvg'] = (solar_power['barometerMax'] + solar_power['barometerMin']) / 2

"""To reduce multicollinearity between related atmospheric variables, maximum and minimum values were averaged. This improves interpretability and stabilizes regression estimates

#### Data Prep
"""

atmo_cols = ['cloudAvg', 'humidityAvg',
             'precip', 'rainTotal', 'barometerAvg', 'solarDailyTotal']

solar_atmo = solar_power[atmo_cols].copy()

solar_atmo.isna().sum()

solar_atmo_clean = solar_atmo.dropna(subset=['solarDailyTotal', 'cloudAvg',
                                             'humidityAvg', 'barometerAvg'])

"""## EDA"""

# correlation matrix
corr_matrix = solar_atmo_clean.corr()

# visualize correlation with solar production
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix[['solarDailyTotal']].sort_values(by='solarDailyTotal', ascending=False),
            annot=True, cmap='coolwarm')
plt.title("Correlation of Atmospheric Variables with Solar Energy Production")
plt.show()

"""This heatmap shows the correlation between key atmospheric variables and daily solar energy production. Cloud cover has the strongest positive association with solar output (0.69), suggesting that it is the most influential predictor in the dataset. Barometric pressure also shows a moderate positive relationship (0.37), while humidity is moderaletly negatively correlated (-0.53), indicating lower solar production on more humid days. Precipitation and total rainfall have weak negative correlations (-.10 and -.16, respectively), suggesting a smaller direct relationship with solar energy in this dataset. Overall, the results indicate that cloud cover and humidity are the most important atmospheric factors influencing solar energy production, while precipitation-related variables play a smaller role."""

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

sns.scatterplot(ax=axes[0], x='cloudAvg', y='solarDailyTotal', data=solar_atmo_clean)
axes[0].set_title("Avg Cloud Cover vs Solar Energy")

sns.scatterplot(ax=axes[1], x='humidityAvg', y='solarDailyTotal', data=solar_atmo_clean)
axes[1].set_title("Avg Humidity vs Solar Energy")

sns.scatterplot(ax=axes[2], x='barometerAvg', y='solarDailyTotal', data=solar_atmo_clean)
axes[2].set_title("Avg Barometric Pressure vs Solar Energy")

plt.tight_layout()
plt.show()

predictors = ['cloudAvg', 'humidityAvg', 'precip', 'rainTotal', 'barometerAvg']

X = solar_atmo_clean[predictors].copy()
y = solar_atmo_clean['solarDailyTotal']

X = X.dropna()
y = y[X.index]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

lasso = LassoCV(cv=5, random_state=42)
lasso.fit(X_scaled, y)

coef_df = pd.DataFrame({
    'Variable': predictors,
    'Coefficient': lasso.coef_
})

print("Optimal alpha:", lasso.alpha_)
print(coef_df.sort_values(by='Coefficient', key=abs, ascending=False))

# chart the results
coef_df = coef_df.sort_values(by='Coefficient')

plt.figure(figsize=(8,5))

plt.barh(coef_df['Variable'], coef_df['Coefficient'])

plt.title('LASSO Regression Coefficients (Standardized Features)')
plt.xlabel('Coefficient Value')
plt.ylabel('Variable')

plt.axvline(0, color='black', linewidth=1)

plt.tight_layout()
plt.show()

"""LASSO regression was used to identify the most influential atmospheric variables affecting solar energy production. After reducing multicollinearity by averaged related predictors like min/max values of cloud cover, humidity, and barometric pressure, the model indicates that cloud cover is the strongest predictor of solar energy output, followed by humidity. Barometric pressure and precipitation variables have comparatively smaller effects.

However, the positive coefficients for cloud cover and humidity should be interpreted with caution. These variables are highly correlated with seasonal patterns, meaning that their effects may reflect broader seasonal variation rather than direct physical increases in solar production. Despite this, the results consistently show that cloud cover is the most important atmospheric factor influencing solar energy generation in the dataset.

# Question 2: How much does cloud cover reduce daily solar energy production?

# Question 3: How do snowfall and snowpack depth affect solar energy production?
"""

snow_solar = (
    solar_power[['date', 'solarDailyTotal', 'snowfall', 'snowpack']]
    # drop rows w/ NaN in all target numeric cols
    .dropna(subset=['snowfall', 'snowpack', 'solarDailyTotal'])
)

snow_solar.head()

"""### EDA
#### Summary statistics
"""

snow_solar[['solarDailyTotal', 'snowfall', 'snowpack']].describe()

"""Let's identify months with any snowfall to get informative summary stats for snow variables."""

# find months with non-zero snowpack
snow_months = snow_solar[snow_solar['snowpack'] > 0]['date'].dt.month.unique()

# summary stats for months w/ persistent snowpack
snow_solar[snow_solar['date'].dt.month.isin(snow_months)].describe()

# summary stats for months w/o persistent snowpack
snow_solar[~snow_solar['date'].dt.month.isin(snow_months)].describe()

"""Let's make a new df for months where snowfall is possible so we can more cleanly visualize the relationship between snowfall/snowpack depth on solar production."""

snow_solar_analysis = snow_solar[snow_solar['date'].dt.month.isin(snow_months)].copy()

snow_solar_analysis.head()

"""**#### Distribution of daily solar production**

*Note: Referenced Plotly documentation to format axes/layout, add LOWESS trendline, etc*

URLs:


*   https://plotly.com/python/reference/layout/xaxis/
*   https://plotly.com/python/reference/layout/yaxis/
*   https://plotly.com/python/reference/layout/
*   https://plotly.com/python/linear-fits/





"""

# create dictionary to add outline around histograms
hist_outline = {
    'line': {
        'color': 'black',
        'width': 1
    }
}

# make histogram
solar_hist = px.histogram(
    snow_solar_analysis,
    x='solarDailyTotal',
    barmode='overlay',
    title='Distribution of Daily Solar Energy Production (Watt-Hours)',
    labels={'solarDailyTotal': 'Daily Solar Production (Wh)'}
).update_traces(
    marker=hist_outline # add outline around bins
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

solar_hist.show()

# distribution of snowfall (non-0 days only to evaluate shape during periods w/ active snowfall)
snowfall_hist = px.histogram(
    snow_solar_analysis[snow_solar_analysis['snowfall'] > 0],
    x='snowfall',
    barmode='overlay',
    height=400,
    title='Distribution of Daily Snowfall (non-0 days only)',
    labels={'snowfall': '24-hr Snowfall (in.)'}
).update_traces(
    marker=hist_outline # add outline around bins
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowfall_hist.show()

"""#### **Snow vs. No-Snow days**
A logical comparison to make is whether days with any measurable recorded snowfall produce less solar energy than days without.
"""

# create dummy variable `snow_day` for whether any measurable snowfall
snow_solar_analysis['snow_day'] = np.where(
    snow_solar_analysis['snowfall'] > 0,
    'Snow day',
    'No snow'
)

# look at counts
snow_solar_analysis['snow_day'].value_counts()

"""Out of 1297 total days with valid data during months with persistent snowpack, 536 had recorded snowfall and 761 did not."""

# make violin plot to visualize (data is high density)
solar_by_snowday = px.violin(
    snow_solar_analysis,
    x='snow_day',
    y='solarDailyTotal',
    color='snow_day',
    box=True,
    points='all',
    height=500,
    title='Solar Production: Snow vs. No-Snow Days',
    labels={
        'solarDailyTotal': 'Daily Solar Production (Wh)',
        'snow_day': ''
    }
).update_traces(
    marker_opacity=0.5
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black',
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)',
    # hide legend (b/c redundant)
    showlegend=False
)

solar_by_snowday.show()

# calculate summary stats for both groups
(
    snow_solar_analysis
    .groupby('snow_day')
    .solarDailyTotal
    .describe()
    .round(2)
)

"""There is a substantial difference in production between snow (median: ~915 Wh) and non-snow days (median: ~10337 Wh). Violin plot reveals a spike in 0/near-0 solar production days for snow days, but there's more overlap at higher production values.

#### **Scatterplots - Snowfall & Snowpack vs. Solar production**
"""

snowfall_vs_solar = px.scatter(
    snow_solar_analysis,
    x='snowfall',
    y='solarDailyTotal',
    opacity=.5,
    # use LOWESS for trendline (outlier at 24-hr snowfall of ~14.3 in. causes OLS line to go negative)
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Daily Snowfall vs. Solar Energy Production',
    labels={
        'snowfall': '24-hr Snowfall (in.)',
        'solarDailyTotal': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowfall_vs_solar.show()

print(f"There are {snow_solar_analysis.query('snow_day == "No snow"').shape[0]} days with 0 inches of recorded 24-hr snowfall.")

"""Let's make another scatterplot, but without 'No snow' (as to better understand the relationship between snowfall and solar production)."""

snowfall_vs_solar_filter = px.scatter(
    snow_solar_analysis.query('snow_day == "Snow day"'),
    x='snowfall',
    y='solarDailyTotal',
    opacity=0.75,
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Daily Snowfall vs. Solar Energy Production (days w/ > 0 in. only)',
    labels={
        'snowfall': '24-hr Snowfall (in.)',
        'solarDailyTotal': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowfall_vs_solar_filter.show()

"""Both scatterplots for daily snowfall show a sharp decline in solar production as 24-hr Snowfall increases, which could be caused by a combination of cloud cover (to be investigated later!) and snow blocking the panel.

Looking at snowpack next...
"""

snowpack_vs_solar = px.scatter(
    snow_solar_analysis,
    x='snowpack',
    y='solarDailyTotal',
    opacity=.5,
    # use LOWESS again
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Snowpack Depth vs. Solar Energy Production',
    labels={
        'snowpack': 'Snowpack Depth (in.)',
        'solarDailyTotal': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowpack_vs_solar.show()

print(f"There are {snow_solar_analysis.query('snowpack == 0').shape[0]} days with a snowpack of 0 inches!")

"""Similarly to what we did with snowfall, let's make another scatterplot, this time excluding days with no snowpack (as to better understand the relationship between persistent snowpack and solar production)."""

snowpack_vs_solar_filter = px.scatter(
    snow_solar.query('snowpack > 0'),
    x='snowpack',
    y='solarDailyTotal',
    opacity=0.5,
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Snowpack Depth vs. Solar Energy Production (days w/ > 0 in. only)',
    labels={
        'snowpack': 'Snowpack Depth (in.)',
        'solarDailyTotal': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowpack_vs_solar_filter.show()

"""The relatively flat (if not descending) LOWESS line for solar production for days with > 0 in. snowpack depth suggests that our hypothesis that reflected light could increase solar production is incorrect.

#### **Correlation matrix**

Before starting to build a model, we check correlation strength between each snow variable and solar production, as well as between snow variables (check for multicollinearity, etc.).
"""

# make heatmap
plt.figure(figsize=(7,6))

sns.heatmap(
    snow_solar_analysis[['solarDailyTotal', 'snowfall', 'snowpack']].corr(method='spearman'),
    cmap='coolwarm',
    vmax=1,
    vmin=-1,
    annot=True,
    fmt='.2f',
    linewidth=0.5
)

plt.title('Correlation matrix: Solar Production & Snow Variables')

plt.tight_layout()
plt.show()

"""Both snow variables have moderate/strong negative correlations with solar production. Additionally, they are moderately correlated with one another, indicating some multicollinearity (i.e., days with new snowfall tend to have more snowpack, vice-versa), but not strong to the extent that a regression model would be destablized. This suggests LASSO is likely to prefer one predictor over the other when penalized.

*Note: Moderate/strong negative correlation between snowpack and solar production indicates data doesn't support hypothesis that snowpack increases production via reflected light.*

### **Machine Learning**
#### **Method #1: MLR**

Goal: Estimate the effect of snowfall and snowpack on daily solar energy production

Let's keep using the snow_solar_analysis df so that we're investigating how the presence of snow (persistent or fresh) impacts solar production as compared to a winter day without snow.
"""

# grab features
X_snow = snow_solar_analysis[['snowfall', 'snowpack']]
# and target
y_snow = snow_solar_analysis['solarDailyTotal']

# do 80/20 train/test split (w/ seed set for reproducibility)
X_train_snow, X_test_snow, y_train_snow, y_test_snow = train_test_split(X_snow, y_snow, test_size=.2, shuffle=True, random_state=3870)

# start the 'engine'
snow_solar_mlr = LinearRegression()

# fit the model
snow_solar_mlr.fit(
    X=X_train_snow,
    y=y_train_snow
)

# evaluate - coefficients
snow_solar_mlr_coeff = pd.DataFrame({
    'feature': X_snow.columns,
    'estimate': snow_solar_mlr.coef_
})

snow_solar_mlr_coeff

# evaluate - R2
r2_train = round(snow_solar_mlr.score(X_train_snow, y_train_snow), 3)
r2_test = round(snow_solar_mlr.score(X_test_snow, y_test_snow), 3)

print(f"R2 (train): {r2_train}")
print(f"R2 (test): {r2_test}")

"""Both coefficients are negative as expected; more snowfall and deeper snowpack both predict less solar production.

The R2 (13.6%) is about what should be expected given the moderate/strong correlations we saw earlier, and supports the idea that while the snow variables are relevant predictors, a large portion of variation in solar production is driven by other factors not included in the model.

The minimal difference between train/test R2 indicates the model generalizes well (low variance), but the low R2 values indicate it's bias-heavy on the bias/variance trade-off spectrum.

Let's take a look at the residuals.
"""

# calculate residuals
y_hat_snow = snow_solar_mlr.predict(X=X_test_snow)
res_snow = y_test_snow.values - y_hat_snow

# make residual plot to check mlr assumptions & conditions
snow_solar_mlr_res = px.scatter(
    x=y_hat_snow,
    y=res_snow,
    opacity=0.5,
    height=500,
    labels={
        'x': 'Predicted Solar Production (Wh)',
        'y': 'Residual'
    },
    title='Residual Plot: MLR (Snowfall & Snowpack)'
).add_hline(
    y=0,
    line_width=1.5,
    line_color='black',
    line_dash='dash'
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snow_solar_mlr_res.show()

"""The clear hetereoskedasticity in the residual plot makes sense given the high density of low production on snowdays and the wide spread on non-snow days earlier observed. As snow variables are the only predictors, the model predicts ~12k Wh for any non-snow day (resulting in the dense stack of points at ~12k Wh), while actual production varies widly from factors not included in the model.

The hetereoskedasticity (errors growing larger at higher predicted production values) supports the notion that while snow variables do negatively impact solar production, they're insufficient alone to explain the variance on days with high-production. Adding additional atmospheric predictors (e.g., cloud cover) and utilizing LASSO regularization will be necesary to address the unmodeled variance.
"""