# -*- coding: utf-8 -*-
"""Q3-4_Data_Science_Draft_May2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7gEqDXPxvycjjP5Bvx_peF5St98L1Dh

## Question

> **How do snowfall and snowpack depth affect solar energy production?**

Active snowfall is likely to cause a decreased in solar energy production. This could be via a combination of accumulated snow physically blocking the panel and increased cloud cover reducing sunlight. Potentially, persistent snowpack (snow has high albedo) could increase solar production by reflecting sunlight onto the panel.

### Imports:
"""

# import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

"""### Data Cleaning:

#### Load raw data
"""

# import the data
precipitation = pd.read_csv("Data/precipitation.csv")
solar = pd.read_csv("Data/solar.csv")
sun = pd.read_csv("Data/sun.csv")
weather = pd.read_csv("Data/weather.csv")

precipitation.head()

solar.head()

sun.head()

weather.head()

"""#### Standardize date columns"""

# making precipitation's "Date" lowercase to match all datasets
precipitation.rename(columns={"Date": "date"}, inplace=True)

# convert all date cols to datetime objects
weather['date'] = pd.to_datetime(weather['date'])
precipitation['date'] = pd.to_datetime(precipitation['date'])
sun['date'] = pd.to_datetime(sun['date'])
solar['date'] = pd.to_datetime(solar['date']).dt.normalize()

"""#### Aggregate solar to daily totals

Precipatation, weather, and sun are all measured daily, but solar is measured every 15 minutes. To align solar's granularity with the other data, we sum all readings within each day.
"""

solar_daily = (
    solar
    .groupby('date', as_index=False)['value']
    .sum()
    .rename(columns={'value': 'daily_total'})
)

solar_daily.head()

"""#### Merge"""

solar_power = (
    solar_daily
    .merge(weather, on='date', how='inner')
    .merge(precipitation, on='date', how='inner')
    .merge(sun, on='date', how='inner')
)

solar_power.info()
solar_power.describe()

# need to convert snow-related cols to numeric
cols_to_convert = ['Precip in.', '24-hr Snowfall in.', 'Snowpack Depth in.']

for col in cols_to_convert:
    # replace 'T' (likely representing a trace amount) with 0.001 in.
    solar_power['24-hr Snowfall in.'] = solar_power['24-hr Snowfall in.'].replace('T', 0.001)
    # convert to numeric (set non-convertables to NaN)
    solar_power[col] = pd.to_numeric(solar_power[col], errors='coerce')

solar_power.info()

"""Let's create a new dataframe (`snow_solar`) with precipitation and solar production data, only keeping rows with non-missing values for all three snow variables *and* solar production)."""

snow_solar = (
    solar_power[['date', 'daily_total', '24-hr Snowfall in.', 'Snowpack Depth in.']]
    # rename cols from precip to be shorter
    .rename(
        columns={
            '24-hr Snowfall in.': 'snowfall',
            'Snowpack Depth in.': 'snowpack',
        }
    )
    # drop rows w/ NaN in all target numeric cols
    .dropna(subset=['snowfall', 'snowpack', 'daily_total'])
)

snow_solar.head()

print(f'There are {snow_solar.query('daily_total == 0').shape[0]} days with 0 reported solar generation')

"""Days with no solar generation may be due to an offline sensor, but also could be the result of snow temporarily blocking the panel. Let's keep days with no solar generation, and reference `weather`/`sun` when tackling our final question(s)."""

# # drop days where solar reported 0 (likely offline sensor or similar)
# snow_solar = snow_solar[snow_solar['daily_total'] > 0].reset_index(drop=True)

# snow_solar['daily_total'].min() != 0

"""### EDA:
#### Summary statistics
"""

snow_solar[['daily_total', 'snowfall', 'snowpack']].describe()

"""Let's identify months with any snowfall to get informative summary stats for snow variables."""

# find months with non-0 snowpack
snow_months = snow_solar[snow_solar['snowpack'] > 0]['date'].dt.month.unique()

# summary stats for months w/ persistent snowpack
snow_solar[snow_solar['date'].dt.month.isin(snow_months)].describe()

# summary stats for months w/o persistent snowpack
snow_solar[~snow_solar['date'].dt.month.isin(snow_months)].describe()

"""Let's make a new df for months where snowfall is possible so we can more cleanly visualize the relationship between snowfall/snowpack depth on solar production."""

snow_solar_analysis = snow_solar[snow_solar['date'].dt.month.isin(snow_months)].copy()

snow_solar_analysis.head()

"""#### Distribution of daily solar production

*Note: Referenced Plotly documentation to format axes/layout, add LOWESS trendline, etc.*

> URLs:
> - https://plotly.com/python/reference/layout/xaxis/
> - https://plotly.com/python/reference/layout/yaxis/
> - https://plotly.com/python/reference/layout/
> - https://plotly.com/python/linear-fits/*
"""

# create dictionary to add outline around histograms
hist_outline = {
    'line': {
        'color': 'black',
        'width': 1
    }
}

# make histogram
solar_hist = px.histogram(
    snow_solar_analysis,
    x='daily_total',
    barmode='overlay',
    title='Distribution of Daily Solar Energy Production (Watt-Hours)',
    labels={'daily_total': 'Daily Solar Production (Wh)'}
).update_traces(
    marker=hist_outline # add outline around bins
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

solar_hist.show()

# distribution of snowfall (non-0 days only to evaluate shape during periods w/ active snowfall)
snowfall_hist = px.histogram(
    snow_solar_analysis[snow_solar_analysis['snowfall'] > 0],
    x='snowfall',
    barmode='overlay',
    height=400,
    title='Distribution of Daily Snowfall (non-0 days only)',
    labels={'snowfall': '24-hr Snowfall (in.)'}
).update_traces(
    marker=hist_outline # add outline around bins
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowfall_hist.show()

"""#### Snow vs. No-Snow days

A logical comparison to make is whether days with any measurable recorded snowfall produce less solar energy than days without.
"""

# create dummy variable `snow_day` for whether any measurable snowfall
snow_solar_analysis['snow_day'] = np.where(
    snow_solar_analysis['snowfall'] > 0,
    'Snow day',
    'No snow'
)

# look at counts
snow_solar_analysis['snow_day'].value_counts()

"""Out of 1297 total days with valid data during months w/ persistent snowpack, 536 had recorded snowfall and 761 did not!"""

# make violin plot to visualize (data is high density)
solar_by_snowday = px.violin(
    snow_solar_analysis,
    x='snow_day',
    y='daily_total',
    color='snow_day',
    box=True,
    points='all',
    height=500,
    title='Solar Production: Snow vs. No-Snow Days',
    labels={
        'daily_total': 'Daily Solar Production (Wh)',
        'snow_day': ''
    }
).update_traces(
    marker_opacity=0.5
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black',
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)',
    # hide legend (b/c redundant)
    showlegend=False
)

solar_by_snowday.show()

# calculate summary stats for both groups
(
    snow_solar_analysis
    .groupby('snow_day')
    .daily_total
    .describe()
    .round(2)
)

"""There is a substantial difference in production between snow (median: ~915 Wh) and non-snow days (median: ~10337 Wh). Violin plot reveals a spike in 0/near-0 solar production days for snow days, but there's more overlap at higher production values.

#### Scatterplots - Snowfall & Snowpack vs. Solar production
"""

snowfall_vs_solar = px.scatter(
    snow_solar_analysis,
    x='snowfall',
    y='daily_total',
    opacity=.5,
    # use LOWESS for trendline (outlier at 24-hr snowfall of ~14.3 in. causes OLS line to go negative)
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Daily Snowfall vs. Solar Energy Production',
    labels={
        'snowfall': '24-hr Snowfall (in.)',
        'daily_total': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowfall_vs_solar.show()

print(f"There are {snow_solar_analysis.query('snow_day == "No snow"').shape[0]} days with 0 inches of recorded 24-hr snowfall.")

"""Let's make another scatterplot, but without 'No snow' (as to better understand the relationship between snowfall and solar production)."""

snowfall_vs_solar_filter = px.scatter(
    snow_solar_analysis.query('snow_day == "Snow day"'),
    x='snowfall',
    y='daily_total',
    opacity=0.75,
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Daily Snowfall vs. Solar Energy Production (days w/ > 0 in. only)',
    labels={
        'snowfall': '24-hr Snowfall (in.)',
        'daily_total': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowfall_vs_solar_filter.show()

"""Both scatterplots for daily snowfall show a sharp decline in solar production as 24-hr Snowfall increases, which could be caused by a combination of cloud cover (to be investigated later!) and snow blocking the panel.

Looking at snowpack next...
"""

snowpack_vs_solar = px.scatter(
    snow_solar_analysis,
    x='snowpack',
    y='daily_total',
    opacity=.5,
    # use LOWESS again
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Snowpack Depth vs. Solar Energy Production',
    labels={
        'snowpack': 'Snowpack Depth (in.)',
        'daily_total': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowpack_vs_solar.show()

print(f"There are {snow_solar_analysis.query('snowpack == 0').shape[0]} days with a snowpack of 0 inches!")

"""Similarly to what we did with snowfall, let's make another scatterplot, this time excluding days with no snowpack (as to better understand the relationship between persistent snowpack and solar production)."""

snowpack_vs_solar_filter = px.scatter(
    snow_solar.query('snowpack > 0'),
    x='snowpack',
    y='daily_total',
    opacity=0.5,
    trendline='lowess',
    trendline_color_override='red',
    height=500,
    title='Snowpack Depth vs. Solar Energy Production (days w/ > 0 in. only)',
    labels={
        'snowpack': 'Snowpack Depth (in.)',
        'daily_total': 'Daily Solar Production (Wh)'
    }
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snowpack_vs_solar_filter.show()

"""The relatively flat (if not descending) LOWESS line for solar production for days with > 0 in. snowpack depth suggests that our hypothesis that reflected light could increase solar production is incorrect.

#### Correlation matrix

Before starting to build a model, we check correlation strength between each snow variable and solar production, as well as between snow variables (check for multicollinearity, etc.).
"""

# make heatmap
plt.figure(figsize=(7,6))

sns.heatmap(
    snow_solar_analysis[['daily_total', 'snowfall', 'snowpack']].corr(method='spearman'),
    cmap='coolwarm',
    vmax=1,
    vmin=-1,
    annot=True,
    fmt='.2f',
    linewidth=0.5
)

plt.title('Correlation matrix: Solar Production & Snow Variables')

plt.tight_layout()
plt.show()

"""Both snow variables have moderate/strong negative correlations with solar production. Additionally, they are moderately correlated with one another, indicating some multicollinearity (i.e., days with new snowfall tend to have more snowpack, vice-versa), but not strong to the extent that a regression model would be destablized. This suggests LASSO is likely to prefer one predictor over the other when penalized.

*Note: Moderate/strong negative correlation between snowpack and solar production indicates data doesn't support hypothesis that snowpack increases production via reflected light.*

### Machine Learning

#### Method #1: MLR
Goal -> Estimate the effect of snowfall and snowpack on daily solar energy production (inference)

Let's keep using the `snow_solar_analysis` df so that we're investigating how the presence of snow (persistent or fresh) impacts solar production as compared to a winter day without snow.
"""

# grab features...
X_snow = snow_solar_analysis[['snowfall', 'snowpack']]
# ...and target
y_snow = snow_solar_analysis['daily_total']

# do 80/20 train/test split for both (w/ class seed for reproducibility)
X_train_snow, X_test_snow, y_train_snow, y_test_snow = train_test_split(X_snow, y_snow, test_size=.2, shuffle=True, random_state=3870)

# start the 'engine'
snow_solar_mlr = LinearRegression()

# fit the model
snow_solar_mlr.fit(
    X=X_train_snow,
    y=y_train_snow
)

# evaluate - coefficients
snow_solar_mlr_coeff = pd.DataFrame({
    'feature': X_snow.columns,
    'estimate': snow_solar_mlr.coef_
})

snow_solar_mlr_coeff

# evaluate - R2
r2_train = round(snow_solar_mlr.score(X_train_snow, y_train_snow), 3)
r2_test = round(snow_solar_mlr.score(X_test_snow, y_test_snow), 3)

print(f"R2 (train): {r2_train}")
print(f"R2 (test): {r2_test}")

"""Both coefficients are negative as expected; more snowfall and deeper snowpack both predict less solar production.

The R2 (13.6%) is about what should be expected given the moderate/strong correlations we saw earlier, and supports the idea that while the snow variables are relevant predictors, a large portion of variation in solar production is driven by other factors not included in the model.

The minimal difference between train/test R2 indicates the model generalizes well (low variance), but the low R2 values indicate it's bias-heavy on the bias/variance trade-off spectrum.

Let's take a look at the residuals...
"""

# calculate residuals
y_hat_snow = snow_solar_mlr.predict(X=X_test_snow)
res_snow = y_test_snow.values - y_hat_snow

# make residual plot to check mlr assumptions & conditions
snow_solar_mlr_res = px.scatter(
    x=y_hat_snow,
    y=res_snow,
    opacity=0.5,
    height=500,
    labels={
        'x': 'Predicted Solar Production (Wh)',
        'y': 'Residual'
    },
    title='Residual Plot: MLR (Snowfall & Snowpack)'
).add_hline(
    y=0,
    line_width=1.5,
    line_color='black',
    line_dash='dash'
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

snow_solar_mlr_res.show()

"""The clear hetereoskedasticity in the residual plot makes sense given the high density of low production on snowdays and the wide spread on non-snow days earlier observed. As snow variables are the only predictors, the model predicts ~12k Wh for any non-snow day (resulting in the dense stack of points at ~12k Wh), while actual production varies widly from factors not included in the model.

 The hetereoskedasticity (errors growing larger at higher predicted production values) supports the notion that while snow variables *do* negatively impact solar production, they're insufficient alone to explain the variance on days with high-production. Adding additional atmospheric predictors (e.g., cloud cover) and utilizing LASSO regularization will be necesary to address the unmodeled variance.

# Question 4: Which weather variable has the strongest relationship with solar energy production?

Our EDA reveals that all weather variables have some relationship with solar production. However, as these variables are often highly correlated, they cannot be effectively evaluated individually / in isolation. Further, the MLR model for the impact of snow variables on solar production shows significant heteroskedasticity, indicating a simple linear model doesn't effectively capture the relationship between weather variables and solar production. To identify a single strongest predictor, let's use LASSO regularization and OLS regression to isolate linear effects, a Random Forest to capture non-linear effects, and compare the results of both methods.

### LASSO
To address the hetereoskedasticity observed in prior questions (i.e., explain more variance in solar production) while keeping our focus on linear relationships, adding more predictors is a natural choice. However, doing so increases the risk of multicollinearity issues and overfitting our model (high variance on the bias-variance tradeoff spectrum). To mitigate this risk and identify the most important weather variables, let's use LASSO to penalize redundant predictors and 'push' their coefficients towards zero.
"""

solar_power.describe()

"""### Train/Test Split"""

# ensure no NaNs in weather var columns
# solar_power = solar_power.dropna(subset=['temperatureMax', 'temperatureMin', 'rainTotal', 'rainPercent', 'barometerMax', 'barometerMin', 'cloudMax', 'cloudMin', 'humidityMax', 'humidityMin', 'Precip in.', '24-hr Snowfall in.', 'Snowpack Depth in.'])
q4_feaures = [
    'temperatureMax', 'temperatureMin', 'rainTotal', 'rainPercent', 'barometerMax',
    'barometerMin', 'cloudMax', 'cloudMin', 'humidityMax', 'humidityMin',
    'Precip in.', '24-hr Snowfall in.', 'Snowpack Depth in.'
]

# grab features...
X_strongest = solar_power[['temperatureMax', 'temperatureMin', 'rainTotal', 'rainPercent', 'barometerMax', 'barometerMin', 'cloudMax', 'cloudMin', 'humidityMax', 'humidityMin', 'Precip in.', '24-hr Snowfall in.', 'Snowpack Depth in.']]
# ...and target
y_strongest = solar_power['daily_total']

# do 80/20 train/test split for both (w/ class seed for reproducibility)
X_train_strongest, X_test_strongest, y_train_strongest, y_test_strongest = train_test_split(X_strongest, y_strongest, test_size=.2, shuffle=True, random_state=3870)

"""### Standardization

Weather variables are in varying units, so comparing coefficients estimated from their 'as-is' values wouldn't be informative/helpful. To resolve this and enable comparison of effect size, let's standardize the weather variables:
"""

from sklearn.preprocessing import StandardScaler

# start engine
scaler = StandardScaler()

# fit scaler for X_train_strongest's mean/sd
scaler.fit(X_train_strongest)

# make scaled train df
X_train_strongest_scaled = (
    pd.DataFrame(
        scaler.transform(X_train_strongest),
        columns = X_train_strongest.columns
    )
)

# verify via mean / sd
pd.DataFrame({
    'mean': np.mean(X_train_strongest_scaled).round(5),
    'sd': np.std(X_train_strongest_scaled)
})

# make scaled test df
X_test_strongest_scaled = (
    pd.DataFrame(
        scaler.transform(X_test_strongest),
        columns = X_test_strongest.columns
    )
)

# check mean / sd
pd.DataFrame({
    'mean': np.mean(X_test_strongest_scaled).round(5),
    'sd': np.std(X_test_strongest_scaled)
})

"""### LASSO Reg w/ CV"""

from sklearn.linear_model import LassoCV
from sklearn.model_selection import RepeatedKFold

"""#### Find Optimal Lambda

As LASSO uses penalization to 'push' less-important variables to 0, let's do K-Fold CV (via `LassoCV`) to find the optimal value of lambda (avoid overfitting):

(Use LassoCV w/ train set of scaled predictors to identify optimal lambda via K-Fold CV )
"""

# setup folds
cv_folds = RepeatedKFold(
    n_splits = 10,
    n_repeats = 10,
    random_state = 3870
)

# FIX ERROR --> NaN's in X_train_strongest_scaled
lasso_search_strongest = (
    LassoCV(
        alphas = np.arange(.01, 50, .01),
        cv = cv_folds,
        n_jobs = -1 # all cores!
    )
    .fit(
        X = X_train_strongest_scaled,
        y = y_train_strongest
    )
)

# visualize results:
lasso_search_strongest_viz = px.line(
    pd.DataFrame({
        'lambda': lasso_search_strongest.alphas,
        # flip rmse order
        'rmse': np.flip(np.sqrt(lasso_search_strongest.mse_path_.mean(axis=1)))
    }),
    x = 'lambda',
    y = 'rmse'
)

lasso_search_strongest_viz

# best choice of lambda is...
print(f'Best choice of lambda is {lasso_search_strongest.alpha_}')

# check out results
lasso_strongest_results = (
    pd.DataFrame({
    'weather variable (feature)': X_train_strongest_scaled.columns,
    'estimate': lasso_search_strongest.coef_.round(2)
    })
    # filter out features w/ slopes of 0
    .query('estimate != 0')
)

lasso_strongest_results

"""(humidityMax is the only feature removed)"""

remaining_features = ['temperatureMax', 'temperatureMin', 'rainTotal', 'rainPercent', 'barometerMax', 'barometerMin', 'cloudMax', 'cloudMin', 'humidityMin', 'Precip in.', '24-hr Snowfall in.', 'Snowpack Depth in.']

"""### OLS
Use these features in an OLS model to understand effect size w/o penalization   
"""

strongest_mlr = (
    LinearRegression()
    # fit with train set
    .fit(
        X = X_train_strongest_scaled[remaining_features],
        y = y_train_strongest
    )
)

# evaluate - coefficients
strongest_mlr_coeff = pd.DataFrame({
    'feature': X_train_strongest_scaled[remaining_features].columns,
    'estimate': strongest_mlr.coef_
})

strongest_mlr_coeff

"""Strongest Weather Variables:
* `temperatureMax`
* `humidityMin`
* `cloudMin`

In terms of linear relationships, sunny (low `cloudMin`), dry (low `humidityMin`), and hot (high `temperatureMax`) days produce the strongest solar production.
"""

# evaluate - R2
r2_train_strongest = round(strongest_mlr.score(X_train_strongest_scaled[remaining_features], y_train_strongest), 3)
r2_test_strongest = round(strongest_mlr.score(X_test_strongest_scaled[remaining_features], y_test_strongest), 3)

print(f"R2 (train): {r2_train_strongest}")
print(f"R2 (test): {r2_train_strongest}")

# visualize via R2 plot:
lasso_strongest_R2 = px.scatter(
    pd.DataFrame({
        'y': y_test_strongest,
        'y_hat': strongest_mlr.predict(
            X = X_test_strongest_scaled[remaining_features]
        )
    }),
    x='y_hat',
    y='y',
    opacity=0.75,
    trendline='ols',
    trendline_color_override='red',
    height=500,
    title=''
).update_xaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showgrid=False,
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

lasso_strongest_R2.show()

"""### Random Forests

* Use all weather variables (multicollinearity is okay!)
"""

from sklearn.model_selection import KFold
# define dict for grid search

hyper_grid = {
    'n_estimators': [10, 50, 100, 200, 300, 400, 500],
    'max_features': np.arange(1, 11, 1).tolist(),
    'max_depth': [1, 2, 10, 20, 50, None]
}

# setup 5-fold cv partition
cv5 = KFold(
    n_splits = 5,
    shuffle = True,
    random_state = 3870
)

# RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn import tree, ensemble

# setup search
strongest_rand_search = RandomizedSearchCV(
    ensemble.RandomForestRegressor(random_state = 3870),
    param_distributions = hyper_grid,
    n_iter = 100,
    cv = cv5,
    random_state = 3870,
    n_jobs = -1
)

import time

# time search
start = time.time()

# train {x} models
strongest_rand_search.fit(X_train_strongest_scaled, y_train_strongest)

end = time.time()
print(f'Search time: {end-start: .3f} sec.')

# evaluate
print(f'Best params: {strongest_rand_search.best_params_}')

print(f'Forest from random search has an R2 of: {strongest_rand_search.best_estimator_.score(X_test_strongest_scaled, y_test_strongest): .3f}')

# feature_importances_

feat_imp_strongest = (
    pd.DataFrame({
        'feature': X_test_strongest_scaled.columns,
        'importance': strongest_rand_search.best_estimator_.feature_importances_
    })
    .sort_values(
        by = 'importance',
        ascending = False
    )
)

feat_imp_strongest

# visualize importance

rf_strongest_feat_imp = px.bar(
    feat_imp_strongest,
    x='feature',
    y='importance',
    barmode='overlay',
    height=400,
    title=''
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black'
).update_layout(
    title={'x': 0.5},
    plot_bgcolor='rgba(0,0,0,0)'
)

rf_strongest_feat_imp.show()

"""### Compare & Evaluate Results

*Can atmospheric and snow conditions predict whether a day will have high or low solar energy production?*
"""

# (calculate OLS 'importance'?)
strongest_mlr_coeff['estimate_abs'] = strongest_mlr_coeff['estimate'].abs()

ols_total_effect = strongest_mlr_coeff['estimate_abs'].sum()

strongest_mlr_coeff['ols_importance'] = strongest_mlr_coeff['estimate_abs'] / ols_total_effect

strongest_mlr_coeff.sort_values(
    by='ols_importance',
    ascending = False
)

ols_imp = strongest_mlr_coeff[['feature', 'ols_importance']]
rf_imp = feat_imp_strongest[['feature', 'importance']].rename(columns={'importance': 'rf_importance'})

ols_vs_rf = (
    pd.merge(
        ols_imp,
        rf_imp,
        on='feature'
    )
    .sort_values(
        by='rf_importance',
        ascending=False
    )
)

ols_vs_rf

ols_vs_rf_melt = (
    ols_vs_rf
    .melt(
        id_vars='feature',
        value_vars=['ols_importance', 'rf_importance'],
        var_name='model',
        value_name='rel_importance'
    )
)

ols_vs_rf_melt

ols_vs_rf_viz = px.bar(
    ols_vs_rf_melt,
    x='feature',
    y='rel_importance',
    color='model',
    barmode='group',
    height=500,
    title='',
    labels={
        'feature': 'Weather Variable',
        'rel_importance': 'Relative Importance'
    }
).update_xaxes(
    showline=True,
    linewidth=1,
    linecolor='black',
    tickangle=45
).update_yaxes(
    showline=True,
    linewidth=1,
    linecolor='black',
    tickformat='.0%'
).update_layout(
    plot_bgcolor='rgba(0,0,0,0)',
    legend=dict(
        yanchor="top",
        y=0.99,
        xanchor="right",
        x=0.99
    )
)

ols_vs_rf_viz.show()

